services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      RUSTFS_REGION: us-east-1
    volumes:
      - rustfs:/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f  http://127.0.0.1:9000/health" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s

  init:
    build: ./docker
    image: services_init:latest
    container_name: init
    depends_on:
      rustfs:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./src:/opt/src
      - ./data/source/:/opt/data
    command: sh -c 'python /opt/src/transform_data.py'

volumes:
  rustfs:
